stages:
 - test
 - build

image: node:10-alpine

test:
 stage: test
 script:
 - npm i
 - npm run lint
 - npm run test
 tags:
 - shared

build:
 stage: build
 script:
 - npm i
 - npm run build
 tags:
 - shared