stages:
 - test
 - build
 - deploy
 - deploy-latest
 - deploy-release

image: node:10

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

test:
 stage: test
 script:
 - yarn install
 - yarn run lint
 - yarn run test
 tags:
 - shared

build:
 stage: build
 script:
 - yarn install
 - yarn run build
 - yarn run build.storybook
 artifacts:
  paths:
  - dist/
  - storybook-static/
 tags:
 - shared

# variables (see inovex-elements/inovex-cloud-environment repo for how to set up the infrastructure):
# * SSH_PRIVATE_KEY: private key to connect to jump host and deploy host
# * DEPLOY_JUMPHOST: ip of the jumphost
# * DEPLOY_HOST: internal ip of the host

.prepare_ssh: &prepare_ssh |
  mkdir -p ~/.ssh
  echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
  echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy:
 stage: deploy
 image: instrumentisto/rsync-ssh:latest
 script:
 - *prepare_ssh
 - rsync -azv -e 'ssh -A -J ubuntu@$DEPLOY_JUMPHOST' dist/ ubuntu@$DEPLOY_HOST:/dev/vdb/stencil-components/dist/$CI_COMMIT_REF_NAME
 - rsync -azv -e 'ssh -A -J ubuntu@$DEPLOY_JUMPHOST' storybook-static/ ubuntu@$DEPLOY_HOST:/dev/vdb/stencil-components/dist/$CI_COMMIT_REF_NAME/storybook
 tags:
 - shared
 only: 
 - master
 - tags

deploy-latest:
 stage: deploy-latest
 image: instrumentisto/rsync-ssh:latest
 script:
 - *prepare_ssh
 - ssh -A -J ubuntu@$DEPLOY_JUMPHOST ubuntu@$DEPLOY_HOST rsync -rtvu --delete /dev/vdb/stencil-components/dist/$CI_COMMIT_REF_NAME/ /dev/vdb/stencil-components/dist/latest
 tags:
 - shared
 only: 
 - tags


# variables:
# * REGISTRY_TOKEN: auth token for publisher user (you can get it by running `npm login --registry https://registry.elements.inovex.io` and copying the token from your `~/.npmrc`)
# * REGISTRY_HOST: host of the registry (currently this should be `registry.elements.inovex.io`)
deploy-release:
 stage: deploy-release
 script:
 - echo "//$REGISTRY_HOST/:_authToken=$REGISTRY_TOKEN" >> ~/.npmrc
 - npm publish --registry https://$REGISTRY_HOST
 tags:
 - shared
 only:
 - tags