stages:
  - deploy
  - link-latest

image: node:12.10.0

upload:
  stage: deploy
  script:
    - apt-get install unzip jq
    - |
      curl
      --url https://api.github.com/repos/inovex/elements/actions/runs/$RUN_ID/artifacts
      --header 'authorization:Bearer ${GITHUB_ACCESS_TOKEN}'
      | jq --raw-output '.artifacts | map(.archive_download_url) | @sh' # Get Download URL's
      | xargs -n1 curl -OJ --location --header 'authorization:Bearer ${GITHUB_ACCESS_TOKEN}' --url # Download Artifacts
    - mkdir -p packages/elements/dist/
    - mkdir -p packages/storybook/dist/
    - unzip elements.zip -d packages/elements/dist/
    - unzip storybook.zip -d packages/storybook/dist/
    - mkdir -p /srv/webhost/dist/$CI_COMMIT_REF_NAME
    - rsync -a packages/elements/dist/ /srv/webhost/dist/$CI_COMMIT_REF_NAME
    - mkdir -p /srv/webhost/dist/$CI_COMMIT_REF_NAME/storybook
    - rsync -a packages/storybook/dist/ /srv/webhost/dist/$CI_COMMIT_REF_NAME/storybook
  tags:
    - elements
    - webhost
    - deploy
  only:
    - master
    - tags

link-latest:
  stage: link-latest
  script:
    - cd /srv/webhost/dist
    - ln -sfn $CI_COMMIT_REF_NAME latest
  tags:
    - elements
    - webhost
    - deploy
  only:
    - tags

publish-npm:
  stage: deploy
  script:
    - yarn config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - yarn lerna publish from-package --yes
  tags:
    - shared
  only:
    - tags



