stages:
 - test
 - build

image: node:10-alpine

test:
 stage: test
 script:
 - yarn install
 - yarn run lint
 - yarn run test
 tags:
 - shared

build:
 stage: build
 script:
 - yarn install
 - yarn run build
 tags:
 - shared