name: Debug

on:
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - run: test -f last_commit_sha.txt
          && echo "sha=$(cat last_commit_sha.txt)" >> $GITHUB_OUTPUT
          || echo "sha=HelloWorld" >> $GITHUB_OUTPUT
