name: Debug

on:
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changed files
      id: changed-dirs
      uses: tj-actions/changed-files@v32
      with:
        dir_names: true
    - name: List affected dirs
      run: |
        for file in ${{ steps.changed-dirs.outputs.all_changed_and_modified_files }}; do
          echo "$file"
        done
    - name: echo dir join1
      id: dir-join
      run: echo "::set-output name=dirStr::${{ join(steps.changed-dirs.outputs.all_changed_and_modified_files) }}"
    - name: Check if storybook or elements was changed
      if: contains(steps.dir-join.outputs.dirStr, 'packages/elements') ||
        contains(steps.dir-join.outputs.dirStr, 'packages/storybook')
      run: echo "hasChanges"
