name: Deploy Unicorn
## The unicorn is public available at elements.inovex.de/unicorn/<BRANCH-NAME>.

on:
  workflow_call:

jobs:
  changeDetection:
    runs-on: ubuntu-latest
    outputs:
      hasChanges: ${{ steps.evaluation.outputs.hasChanges }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      # Cache handling to determine the last commit id of unicorn deployment
      # 1. Load cache file
      # 2. Read SHA from file
      # 3. Check if commit SHA has changed
      # 4. Update cache if necessary
      - name: Get last commit info file from cache
        id: sha-cache
        uses: actions/cache@v3
        with:
          path: last_commit_sha.txt
          key: last-commit-${{ env.GITHUB_REF_NAME_SLUG_URL }}-${{ hashFiles('last_commit_sha.txt') }}
          restore-keys: last-commit-${{ env.GITHUB_REF_NAME_SLUG_URL }}

      - name: Dump cache
        run: echo '${{ toJSON(steps.sha-cache.outputs) }}'

      - name: Read commit sha from file
        id: last-commit
        if: steps.sha-cache.outputs.cache-hit == 'true'
        run: echo "sha=$(cat last_commit_sha.txt)" >> $GITHUB_OUTPUT

      - name: Save commit SHA to cache
        if: steps.last-commit.outputs.sha != github.sha
        run: echo "${{ github.sha }}" > last_commit_sha.txt

      - name : Get last master commit
        id: prev-commit
        if: env.GITHUB_REF_NAME_SLUG_URL == 'master'
        run: echo "sha=$(git rev-parse master~1)" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          base_sha: ${{ steps.last-commit.outputs.sha || github.event.pull_request.base.sha || steps.prev-commit.outputs.sha }}
          files: |
            packages/elements
            packages/storybook

      - name: Print all changed files
        run: echo '${{ toJSON(steps.changed-files.outputs.all_changed_and_modified_files) }}'

      - name: Check if storybook or elements was changed
        id: evaluation
        if: steps.changed-files.outputs.all_changed_and_modified_files != ''
        run: echo "hasChanges=true" >> $GITHUB_OUTPUT

  deploy-unicorn:
    runs-on: ubuntu-latest
    if: ${{ needs.changeDetection.outputs.hasChanges == 'true' }}
    needs: changeDetection
    environment:
      name: github-pages
      url: https://elements.inovex.de/unicorn/${{ env.GITHUB_REF_NAME_SLUG_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Download Storybook artifact
        uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook-dist

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./storybook-dist
          target-folder: unicorn/${{ env.GITHUB_REF_NAME_SLUG_URL  }}
          commit-message: Deploying unicorn ${{ env.GITHUB_REF_NAME_SLUG_URL  }} 🦄
          force: true
