name: 'Publish Release & Deploy'

## Workflow to deploy a new version to version/<TAG_NAME> github pages.
## The version is available at elements.inovex.de/version/<TAG-NAME>

on:
  workflow_dispatch:
  
jobs:
  build:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'release')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/dependencies-install
      - run: npm config set scripts-prepend-node-path true
      - run: yarn build
      - name: Create version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"
      - name: Create release artifacts
        run: npm pack @inovex.de/elements
             && npm pack @inovex.de/elements-angular
             && npm pack @inovex.de/elements-react
             && npm pack @inovex.de/elements-vue
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./*.tgz
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
