name: Deploy landingpage

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install

  test:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install
      - run: yarn lint
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install
      - run: yarn build

      - name: upload storybook artifact
        uses: actions/upload-artifact@v2
        with:
          name: landingpage
          path:
            packages/landingpage/dist/

  deploy-landingpage:
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v2
        with:
          name: landingpage
          path: ./artifact

      # Update the hoste-versions.json and add it to the build artifact.
      - run: |
          find ./version/* -type d -maxdepth 0 | cut -c 11- | jq -R -s -c 'split("\n")[:-1]' > ./artifact/hosted-versions.json
          cat ./artifact/hosted-versions.json
        shell: bash

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./artifact # The folder the action should deploy.
          commit-message: Deploying landingpage
          clean-exclude: |
            version
            unicorn
