name: Deploy Unicorn

## The unicorn is public available at elements.inovex.de/unicorn/<BRANCH-NAME>.

on:
  workflow_run:
    workflows: ["Test & Build"]
    types: [completed]
    branches-ignore: [master]

jobs:
  changeDetection:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      hasChanges: ${{ steps.evaluation.outputs.hasChanges }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      # Cache handling to determine the last commit id of unicorn deployment
      # 1. Load cache file
      # 2. Read SHA from file
      # 3. Check if commit SHA has changed
      # 4. Update cache if necessary
      - name: Get last commit info file from cache
        id: sha-cache
        uses: actions/cache@v3
        with:
          path: last_commit_sha.txt
          key: last-commit-${{ github.event.workflow_run.head_branch }}-${{ github.run_id }}
          restore-keys: last-commit-${{ github.event.workflow_run.head_branch }}
      - uses: andstor/file-existence-action@v1
        id: check-commit-file
        with:
          files: "last_commit_sha.txt"
      - name: Read commit sha from file
        id: last-commit
        if: steps.check-commit-file.outputs.files_exists
        run: echo "sha=$(cat last_commit_sha.txt)" >> $GITHUB_OUTPUT
      - name: Save commit SHA to cache
        if: steps.last-commit.outputs.sha != github.event.workflow_run.head_sha
        run: echo "${{ github.event.workflow_run.head_sha }}" > last_commit_sha.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          base_sha: ${{ steps.last-commit.outputs.sha || github.sha }}
          sha: ${{ github.event.workflow_run.head_sha }}
          files: |
            packages/elements
            packages/storybook
      - name: Print all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file"
          done
      - name: Check if storybook or elements was changed
        id: evaluation
        if: steps.changed-files.outputs.all_changed_and_modified_files != ''
        run: echo "hasChanges=true" >> $GITHUB_OUTPUT

  deploy-unicorn:
    runs-on: ubuntu-latest
    if: ${{ needs.changeDetection.outputs.hasChanges == 'true' }}
    needs: changeDetection
    environment:
      name: github-pages
      url: https://elements.inovex.de/unicorn/${{ steps.dir-regex.outputs.replaced }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download Storybook artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: storybook
          path: storybook-dist

      - name: Create valid dir name
        id: dir-regex
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '[!*();:@&=+$,\/?%#[]]*'
          flags: 'g'
          string: ${{ github.event.workflow_run.head_branch }}
          replace-with: ''

      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./storybook-dist
          target-folder: unicorn/${{ steps.dir-regex.outputs.replaced  }}
          commit-message: Deploying unicorn ${{ steps.dir-regex.outputs.replaced  }} 🦄
          force: true
