name: Test & Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: setup cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/*/*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-lerna-
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install --frozen-lockfile

  test:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/*/*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-lerna-
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: setup cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/*/*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-lerna-
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - if: github.ref == 'refs/heads/master'
        name: upload elements artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements
          path:
            packages/elements/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload elements-react artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements-react
          path:
            packages/elements-react/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload elements-angular artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements-angular
          path:
            packages/elements-angular/dist/
      - name: upload storybook artifact
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path:
            packages/storybook/dist/

  deploy-unicorn:
    runs-on: ubuntu-latest
    name: Unicorn deployment (on dev)
    if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')
    environment:
      name: unicorn
      url: ${{ steps.deploy_unicorn.outputs.deployment_url }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: ./.github/workflows/deploy-storybook
        id: deploy_unicorn
        with:
          deployment_path: unicorn/${{ env.GITHUB_HEAD_REF_SLUG }}
          storybook_artifact_name: storybook
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-version:
    runs-on: ubuntu-latest
    name: Version Deployment (on tags)
    # TODO: Change this to github release (github.event_name == 'release' && github.event.action == 'created')
    # as soon as we use github releases...
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: production
      url: ${{ steps.deploy_unicorn.outputs.deployment_url }}
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x

      - uses: ./.github/workflows/deploy-storybook
        id: deploy_production
        with:
          # Ref slug refers to version number for tags
          # (https://github.com/rlespinasse/github-slug-action/blob/v3.x/docs/slug-variables.md)
          deployment_path: versions/${{ env.GITHUB_HEAD_REF_SLUG }}
          storybook_artifact_name: storybook
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}