name: GitHub CI

on: [push]

jobs:

  security:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: zricethezav/gitleaks-action@master


  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install
      - run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm config set scripts-prepend-node-path true
      - run: yarn install
      - run: yarn lint
      - run: yarn build

      - if: github.ref == 'refs/heads/master'
        name: upload elements artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements
          path:
            packages/elements/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload elements-react artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements-react
          path:
            packages/elements-react/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload elements-angular artifact
        uses: actions/upload-artifact@v2
        with:
          name: elements-angular
          path:
            packages/elements-angular/dist/
      - if: github.ref == 'refs/heads/master'
        name: upload storybook artifact
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path:
            packages/storybook/dist/

  trigger-release:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/heads/master')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Trigger update in GitLab
        run: curl
          --request POST
          --header "PRIVATE-TOKEN:${{ secrets.GITLAB_ACCESS_TOKEN }}"
          ${{ secrets.GITLAB_URL_WITH_ID }}/mirror/pull
      - name: Wait for update
        run: sleep 10
      - name: Trigger Pipeline in GitLab
        run: curl
          --request POST
          --form token="${{ secrets.GITLAB_RELEASE_TRIGGER_TOKEN }}"
          --form ref="${{ github.ref }}"
          --form "variables[ARTIFACT_ID]=true"
          ${{ secrets.GITLAB_URL_WITH_ID }}/trigger/pipeline

