name: Test & Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install

  build:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/install
    - run: yarn build

    - name: Upload all build artifacts
      uses: ./.github/workflows/artifacts-upload

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install
      - run: yarn lint
      - run: yarn test

  snapshot-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - uses: actions/download-artifact@v3
        name: Download Storybook Artifact
        with:
          name: storybook
          path: packages/storybook/dist
      - name: Serve Storybook and run tests
        working-directory: packages/storybook
        run: yarn test:ci
