name: Test & Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/install

  build:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/install
    - run: yarn build

    # Build caches for other workflows
    - name: Upload all build artifacts
      uses: ./.github/workflows/artifacts-upload

  lint:
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install
      - uses: actions/download-artifact@v3
        name: Download Storybook Artifact
        with:
          name: storybook
          path: packages/storybook/dist
      - run: yarn test
